# Generated by Django 4.2.3 on 2023-07-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='header')),
                ('description', models.TextField(verbose_name='description')),
                ('prise', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prise')),
                ('auction', models.BooleanField(help_text='mark can you auction pr or?', verbose_name='auction?')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
    ]
